customers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "customers"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path('user_logout', views.user_logout, name='logout'),

    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('password_reset/done/', views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
]

kicksavenue/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('customers/',include('customers.urls')),
    path('orders/',include('orders.urls')),
    path('accounts/', include('allauth.urls')),  # Include Django-Allauth URLs here

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name="orders"

urlpatterns = [
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('order_complete/',views.order_complete,name="order_complete"),


]

products/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name="products"
urlpatterns = [
    path('',views.index,name='index'),
    path('allproducts/',views.allproducts,name='allproducts'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('men/',views.men,name='men'),
    path('products/men/<str:category>/', views.men_product_list, name='men_product_list'),
    path('products/women/<str:category>/', views.women_product_list, name='women_product_list'),
    path('women/',views.women,name='women'),
    path('product_detail/<str:p>',views.product_detail,name='product_detail'),

]

templates/allproducts.html
{% extends "blank_layout.html" %}
{% load static %}
{% block content %}
<!--to display all  products-->



<div class="colorlib-product">
    <div class="container">
        <div class="row">

        </div>
        <div class="row row-pb-md">
            {% for i in c %}
                {% if forloop.counter0|divisibleby:3 %}
                    {% if not forloop.first %}
                        </div>
                    {% endif %}
                    <div class="row row-pb-md">
                {% endif %}
                <div class="col-lg-4 mb-4 text-center">
                    <div class="product-entry border">
                        <a href="{% url 'products:product_detail' i.name %}" class="prod-img">
                            <img src="{{ i.image.url }}" class="img-fluid small-img" alt="Free html5 bootstrap 4 template" style="height:400px;width:400px">
                        </a>
                        <div class="desc">
                            <h2><a>{{ i.name }}</a></h2>
                            <span class="price">${{ i.price }}</span>
                        </div>
                    </div>
                </div>
                {% if forloop.last %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>




	
{% endblock %}

templates/blank_layout.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<title>Kicks Avenue</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Rokkitt:100,300,400,700" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

		<style>#carouselExampleFade .carousel-inner .carousel-item img {
    height: 700px; /* Adjust height as needed */
    object-fit: cover;
  }



  .btn-overlay {
    position: absolute;
    bottom: 20px; /* Adjust button position as needed */
    left: 50%; /* Adjust button position as needed */
    transform: translateX(-50%);
  }



</style>


	<!-- Animate.css -->
<!--	<link rel="stylesheet" href="{% static 'css/animate.css' %}">-->
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %} ">
	<!-- Ion Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Date Picker -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
	<!-- Flaticons  -->
	<link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
	</head>
	<body>


<div id="page">

<nav class="colorlib-nav navbar navbar-expand-lg navbar-light bg-light" role="navigation">
    <div class="container">
        <a class="navbar-brand" style="font-weight: bold; margin-top: -5px; font-size: 30px;">Kicks Avenue</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'products:index' %}">Home</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'products:men' %}">Men</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'products:women' %}">Women</a>
                </li>
					<li class="nav-item ">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'customers:login' %}">Login</a>
                </li>
				 <li class="nav-item ">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'customers:register' %}">Register</a>
                </li>
                    {% if user.is_authenticated %}
				  <li class="nav-item ">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'customers:logout' %}">Logout</a>
                </li>
                 {% endif %}
                <li class="nav-item ">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'products:contact' %}">Contact</a>
                </li>

				             <li class="nav-item ">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'products:about' %}">About</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" style="font-weight: bold;" href="{% url 'orders:cart' %}">
                        <i class="icon-shopping-cart"></i>[0]
                    </a>
                </li>
			</ul>
			<form class="d-flex" action="" method="get" style="margin-top: 10px;">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" style="width: 150px; height:30px;">
              <button class="btn btn-outline-success" type="submit" style="padding: 2px 5px; font-size: 12px; height: 25px; background-color: gray; color: white; border-color: gray;">Search</button>
             </form>





        </div>
    </div>
</nav>














		{% block content %}

		{% endblock %}









		<footer id="colorlib-footer" role="contentinfo">
			<div class="container">
				<div class="row row-pb-md">
					<div class="col footer-col colorlib-widget">
						<h4>About Footwear</h4>
						<p>Discover stylish and comfortable footwear at Kicks Avenue. From trendy sneakers to elegant heels and durable boots, our curated collection offers high-quality shoes for every occasion. Shop now for the perfect fit and step up your shoe game with us!</p>
						<p>
							<ul class="colorlib-social-icons">
								<li><a href="https://x.com/peekaab007"><i class="icon-twitter"></i></a></li>
								<li><a href="https://www.facebook.com/"><i class="icon-facebook"></i></a></li>
								<li><a href="https://www.linkedin.com/in/arjun-o-s-429620274/"><i class="icon-linkedin"></i></a></li>

							</ul>
						</p>
					</div>
					<div class="col footer-col colorlib-widget">
						<h4>Customer Care</h4>
						<p>
							<ul class="colorlib-footer-links">
								<li><a href="{% url 'products:contact' %}">Contact</a></li>
						        <li><a>+919876543210</a></li>


							</ul>
						</p>
					</div>




					<div class="col footer-col">
						<h4>Contact Information</h4>
						<ul class="colorlib-footer-links">
							<li>Maradu  <br> Kochi Kerala</li>
							<li><a >+919876543210</a></li>
							<li><a>arjunsudha212@gmail.com</a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="copy">
				<div class="row">
					<div class="col-sm-12 text-center">
						<p>
							<span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> by Kicks Avenue All rights reserved
							</span>
					</div>
				</div>
			</div>
		</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="ion-ios-arrow-up"></i></a>
	</div>

	<script src="{% static 'js/jquery.min.js' %}"></script>
   <!-- popper -->
   <script src="{% static 'js/popper.min.js' %}"></script>
   <!-- bootstrap 4.1 -->
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
   <!-- jQuery easing -->
   <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- Owl carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>
	<!-- Date Picker -->
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/function.js' %}"></script>

	</body>
</html>

templates/index.html
{% extends 'blank_layout.html' %}
{% load static %}
{% block content %}
<style>
    .btn {
  display: inline-block;
  padding: 12px 30px;
  font-size: 18px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #007bff;
  border: none;
  border-radius: 50px;
  box-shadow: 0 4px #999;
  transition: background-color 0.3s ease, box-shadow 0.3s ease, transform 0.3s ease;
}

.btn:hover {
  background-color: #0056b3;
}

.btn:active {
  background-color: #0056b3;
  box-shadow: 0 2px #666;
  transform: translateY(2px);
}

.btn-secondary {
  background-color: #6c757d;
}

.btn-secondary:hover {
  background-color: #545b62;
}

.btn-decorative {
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: 1px;
}


</style>
<div style="margin-top: 1px;">
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/women_banner.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/converse.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/nike_banner.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>


		<div class="colorlib-intro">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center">
						<h2 class="intro">It started with a simple idea: Create quality, well-designed products that I wanted myself.</h2>
					</div>
				</div>
			</div>
		</div>


<div class="colorlib-product">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 offset-sm-2 text-center colorlib-heading">
                <h2>Our Products</h2>
            </div>
        </div>
        <div class="row row-pb-md">
            {% for i in c|slice:":6" %}
                {% if forloop.counter0|divisibleby:3 %}
                    {% if not forloop.first %}
                        </div>
                    {% endif %}
                    <div class="row row-pb-md"> <!-- Open a new row -->
                {% endif %}
                <div class="col-lg-4 mb-4 text-center">
                    <div class="product-entry border">
                        <a href="{% url 'products:product_detail' i.name %}" class="prod-img">
                            <img src="{{ i.image.url }}" class="img-fluid small-img" alt="Product Image" style="height:400px;width:400px">
                        </a>
                        <div class="desc">
                            <h2><a>{{ i.name }}</a></h2>
                            <span class="price">${{ i.price }}</span>
                        </div>
                    </div>
                </div>
                {% if forloop.last %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="row">
            <div class="col text-center mt-4">
                <a href="{% url 'products:allproducts' %}" class="btn btn-secondary btn-decorative">Shop all products</a>
            </div>
        </div>
    </div>
</div>

</div>

		</div>

		<div class="colorlib-partner">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
						<h2>Trusted Partners</h2>
					</div>
				</div>
				<div class="row">
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-1.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-2.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-3.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-4.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-5.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
				</div>
			</div>
		</div>

{% endblock %}

templates/login.html
{% extends 'blank_layout.html' %}
{% load static %}
{% block content %}

<div class="signin-container">
    <div class="image-container">
        <img src="{% static 'images/nike_login.jpg' %}" alt="Sign In Image">
    </div>
    <div class="signin-form">
        <h2>Login</h2>
        <!-- Display error messages here -->
        {% if messages %}
            <div class="error-messages">
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label>
                    <input type="email" name="e" placeholder="Email" required>
                </label>
            </div>
            <div class="form-group">
                <label for="password">
                    <input type="password" id="password" name="p" placeholder="Password" required>
                </label>
            </div>
            <button type="submit">Login</button>
        </form>
        <div class="alternative-options">
            <a href="{% url 'customers:password_reset' %}">Forget Password?</a><br>
            <a href="{% url 'customers:register' %}">Don't have an account?</a>
        </div>
    </div>
</div>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f9f9f9;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .signin-container {
        display: flex;
        background: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        max-width: 900px;
        width: 100%;
        margin: 40px auto;
    }

    .image-container {
        display: none; /* Hide the image container by default for smaller screens */
        flex: 1;
    }

    .image-container img {
        max-width: 100%;
        height: auto;
    }

    .signin-form {
        padding: 40px;
        flex: 1;
    }

    .signin-form h2 {
        margin-bottom: 20px;
        font-size: 24px;
        font-weight: bold;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-group label {
        display: flex;
        align-items: center;
    }

    .form-group input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        outline: none;
        font-size: 16px;
    }

    .form-group input:focus {
        border-color: #007bff;
    }

    button {
        width: 100%;
        padding: 15px;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
        color: #fff;
        font-size: 16px;
        cursor: pointer;
        margin-top: 20px;
    }

    button:hover {
        background-color: #0056b3;
    }

    .alternative-options {
        text-align: center;
        margin-top: 20px;
    }

    .alternative-options a {
        color: #007bff;
        text-decoration: none;
    }

    .alternative-options a:hover {
        text-decoration: underline;
    }

    .error-messages {
        background-color: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 20px;
    }

    @media (min-width: 768px) {
        .image-container {
            display: block; /* Show the image container on larger screens */
        }
    }
</style>

{% endblock %}

templates/men.html
{% extends 'blank_layout.html' %}
{% load static %}
{% block content %}
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col">
                {% if first_category %}
                    <div class="breadcrumbs-img" style="background-image: url('{{ first_category.image.url }}');">
                        <h2>{{ first_category.name }}</h2>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<br>
<br>



<div class="colorlib-featured">
    <div class="container">
        <div class="row">
            {% for i in subcategories %}
                <div class="col-sm-4 text-center">
                    <div class="featured">
                        <div class="featured-img featured-img-2" style="background-image: url({{ i.image.url }});">
                            <h2>{{ i.name }}</h2>
                          <a href="{% url 'products:men_product_list' i.name %}" class="btn btn-primary btn-lg">Shop now</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>




		<div class="colorlib-product">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
						<h2>View All Products</h2>
					</div>
				</div>
				<div class="container">
	<div class="row">
		{% for i in products %}
			<div class="col-md-4 mb-4 text-center">
				<div class="product-entry border">
					<a href="{% url 'products:product_detail' i.name %}" class="prod-img">
						<img src="{{ i.image.url }}" class="img-fluid" alt="Free html5 bootstrap 4 template" style="height:400px;width:400px">
					</a>
					<div class="desc">
						<h2><a >{{ i.name }}</a></h2>
						<span class="price">${{ i.price }}</span>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>






				</div>
			</div>
		</div>

		<div class="colorlib-partner">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
						<h2>Trusted Partners</h2>
					</div>
				</div>
				<div class="row">
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-1.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-2.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-3.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-4.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-5.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
				</div>
			</div>
		</div>

		{% endblock %}

templates/men_product_list.html
{% extends 'blank_layout.html' %}
{% load static %}
{% block content %}

<style>
    .custom-heading {
        position: absolute;
        top: 120px; /* Adjust this value to move the heading down */
        left: 35%;
        transform: translateX(-50%);
    }
</style>

<div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm custom-heading">
    <h2>{{ category }} shoes for men</h2>
</div>

<div class="colorlib-product">
    <div class="container">
        <div class="container">
            <div class="row">
                {% for i in products %}
                    <div class="col-md-4 mb-4 text-center">
                        <div class="product-entry border">
                            <a href="{% url 'products:product_detail' i.name %}" class="prod-img">
                                <img src="{{ i.image.url }}" class="img-fluid" alt="Free html5 bootstrap 4 template" style="height:400px;width:400px">
                            </a>
                            <div class="desc">
                                <h2><a >{{ i.name }}</a></h2>
                                <span class="price">${{ i.price }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="colorlib-partner">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
                <h2>Trusted Partners</h2>
            </div>
        </div>
        <div class="row">
            <div class="col partner-col text-center">
                <img src="{% static 'images/brand-1.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
            </div>
            <div class="col partner-col text-center">
                <img src="{% static 'images/brand-2.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
            </div>
            <div class="col partner-col text-center">
                <img src="{% static 'images/brand-3.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
            </div>
            <div class="col partner-col text-center">
                <img src="{% static 'images/brand-4.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
            </div>
            <div class="col partner-col text-center">
                <img src="{% static 'images/brand-5.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/women.html
{% extends 'blank_layout.html' %}
{% load static %}
{% block content %}

		<div class="breadcrumbs-two">
			<div class="container">
				<div class="row">
					<div class="col">
						{% if second_category %}
                    <div class="breadcrumbs-img" style="background-image: url('{{ second_category.image.url }}'); background-size: cover; background-position: center; max-width: 100%; height: 300px;">
							<h2>{{ second_category.name }}</h2>
						</div>
                      {% endif %}
					</div>
				</div>
			</div>
		</div><br><br>

       <div class="colorlib-featured">
    <div class="container">
        <div class="row">
            {% for i in subcategories %}
                <div class="col-sm-4 text-center">
                    <div class="featured">
                        <div class="featured-img featured-img-2" style="background-image: url({{ i.image.url }});">
                            <h2>{{ i.name }}</h2>
                          <a href="{% url 'products:women_product_list' i.name %}" class="btn btn-primary btn-lg">Shop now</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

		<div class="colorlib-product">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
						<h2>View All Products</h2>
					</div>
				</div>

				<div class="container">
	<div class="row">
		{% for i in products %}
			<div class="col-md-4 mb-4 text-center">
				<div class="product-entry border">
					<a href="{% url 'products:product_detail' i.name %}" class="prod-img">
						<img src="{{ i.image.url }}" class="img-fluid" alt="Free html5 bootstrap 4 template" style="height:400px;width:400px">
					</a>
					<div class="desc">
						<h2><a >{{ i.name }}</a></h2>
						<span class="price">${{ i.price }}</span>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>

			</div>
		</div>

		<div class="colorlib-partner">
			<div class="container">
				<div class="row">
					<div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
						<h2>Trusted Partners</h2>
					</div>
				</div>
				<div class="row">
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-1.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-2.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-3.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-4.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
					<div class="col partner-col text-center">
						<img src="{% static 'images/brand-5.jpg' %}" class="img-fluid" alt="Free html4 bootstrap 4 template">
					</div>
				</div>
			</div>
		</div>

		{% endblock %}